export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    REMOVE_PRODUCT_FROM_CART : "REMOVE_PRODUCT_FROM_CART",
    ADD_PRODUCT_TO_WISHLIST : "ADD_PRODUCT_TO_WISHLIST",
    REMOVE_PRODUCT_FROM_WISHLIST : "REMOVE_PRODUCT_FROM_WISHLIST",
    SET_CART_PRODUCTS: "SET_CART_PRODUCTS",
    SET_WISHLIST_PRODUCTS: "SET_WISHLIST_PRODUCTS",
    ADD_TO_CART : "ADD_TO_CART",
}