export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    ADD_PRODUCT_TO_CART : "ADD_PRODUCT_TO_CART",
    REMOVE_PRODUCT_FROM_CART : "REMOVE_PRODUCT_FROM_CART",
    ADD_PRODUCT_TO_WISHLIST : "ADD_PRODUCT_TO_WISHLIST",
    REMOVE_PRODUCT_FROM_WISHLIST : "REMOVE_PRODUCT_FROM_WISHLIST"
}