apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-app
spec:
  containers:
  - name: mysql-container
    image: mysql:8.0
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: 
    - name: MYSQL_DATABASE
      value: 